"""
Django settings for SYSTEMPROJECT project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

from dotenv import load_dotenv
import dj_database_url

# Load the local .env file early so variables are available
env_path = BASE_DIR / '.env'
load_dotenv(env_path, override=True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-default-key-for-dev')

# SECURITY WARNING: don't run with debug turned on in production!
# Reads DJANGO_DEBUG from .env, defaults to False for safety
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [
    'codeit-attendancesystem.me',
    'www.codeit-attendancesystem.me',
    '104.43.88.93',
    '127.0.0.1',
    'localhost',
]

CSRF_TRUSTED_ORIGINS = [
    'https://codeit-attendancesystem.me',
    'https://www.codeit-attendancesystem.me',
    'http://codeit-attendancesystem.me',
    'http://www.codeit-attendancesystem.me',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'myapp',
    'admin_panel',
    'student_portal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'config.middleware.DDoSProtectionMiddleware',
    'config.middleware.EventStatusAutoUpdateMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')

if not DATABASE_URL:
    logging.warning("No DATABASE_URL environment variable set, and so no databases setup")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=0,
            conn_health_checks=True,
        )
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS — allow frontend to connect during development
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins when DEBUG is True

# DRF settings
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # nice web UI for testing
    ]
}

# Email settings — Gmail SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')       # your Gmail address
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '') # Gmail App Password
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER', 'noreply@code-it.edu')

# File Upload Security — max 5 MB per upload
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024   # 5 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024    # 5 MB

# DDoS Protection Settings
DDOS_RATE_LIMIT = 100        # Max requests per window
DDOS_RATE_WINDOW = 60       # Window in seconds
DDOS_BLOCK_DURATION = 300   # Block duration in seconds
DDOS_MAX_BODY_SIZE = 10     # Max body size in MB
DDOS_WHITELIST_IPS = ['127.0.0.1']

# ---------------------------------------------------------------------------
# Defense Security Configurations
# ---------------------------------------------------------------------------

if not DEBUG:
    # Tell Django it's behind a secure proxy (Nginx/Azure) so it knows HTTPS is active
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # 1. Secure Cookie Configuration
    SESSION_COOKIE_SECURE = True          # Cookies only transmit over HTTPS
    SESSION_COOKIE_HTTPONLY = True        # JavaScript cannot read the cookie (XSS protection)
    SESSION_COOKIE_SAMESITE = 'Lax'       # Prevents Cross-Site Request Forgery (CSRF)
    
    # 2. CSRF Security
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    
    # Only enable HSTS and SSL redirect if we are NOT on a local environment
    # Local environments often use HTTP, and HSTS will permanently break localhost testing
    if os.getenv('WEBSITE_HOSTNAME') or os.getenv('ENVIRONMENT') == 'production':
        # 3. HTTP Strict Transport Security (HSTS)
        SECURE_HSTS_SECONDS = 31536000        # Force HTTPS for 1 year
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True
        SECURE_SSL_REDIRECT = True            # Redirect HTTP -> HTTPS at the Django level
